/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author VICTUS
 */

import javax.swing.JOptionPane;
public class TemplateView extends javax.swing.JFrame {

    /**
     * Creates new form DosenView
     */
//    
//    private DosenControl dosenControl;
    String action = null;
    
    public TemplateView() {
        initComponents();
        setComponent(false);
        setEditDeleteBtn(false);
//        dosenControl = new DosenControl();
//        showData();
    }
    
    public void setComponent(boolean value) {
        idInput.setEnabled(value);
        merkInput.setEnabled(value);
        tahunInput.setEnabled(value);
        noPlatInput.setEnabled(value);
        
        motorRBtn.setEnabled(value);
        mobilRBtn.setEnabled(value);
        
        btnSave.setEnabled(value);
        btnCancel.setEnabled(value);
        
        motorInput.setEnabled(value);
        mobilInput.setEnabled(value);
    }

    public void setEditDeleteBtn(boolean value) {
        btnEdit.setEnabled(value);
        btnDelete.setEnabled(value);
    }
    
    public void setSelect(boolean value){
        mobilRBtn.setSelected(value);
        motorRBtn.setSelected(value);
    }

    public void clearText() {
        idInput.setText("");
        merkInput.setText("");
        tahunInput.setText("");
        noPlatInput.setText("");
        
        motorInput.setText("");
        mobilInput.setText("");
        
        txtSearch.setText("");
    }
    
//    public void showDosen(){
//        showDataTextArea.setText(dosenControl.showDataDosen());
//    }
//    
//    public void inputKosongException() throws InputKosongException{
//        if(nidInput.getText().isEmpty() || namaInput.getText().isEmpty() 
//                || emailInput.getText().isEmpty() 
//                || handphoneInput.getText().isEmpty()) {
//            throw new InputKosongException();
//        }
//    }
//    
//    public void noIndukDosenException() throws NoIndukDosenException {
//        if(nidInput.getText().length() != 5){
//            throw new NoIndukDosenException();
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        containerLabel = new javax.swing.JPanel();
        titleContent = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        containerInputId = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        containerInputMerk = new javax.swing.JPanel();
        merkLabel = new javax.swing.JLabel();
        merkInput = new javax.swing.JTextField();
        containerInputTahun = new javax.swing.JPanel();
        tahunLabel = new javax.swing.JLabel();
        tahunInput = new javax.swing.JTextField();
        containerInputNoPlat = new javax.swing.JPanel();
        noPlatLabel = new javax.swing.JLabel();
        noPlatInput = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        showDataPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showDataTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        containerOptionMobil = new javax.swing.JPanel();
        mobilRBtn = new javax.swing.JRadioButton();
        mobilInput = new javax.swing.JTextField();
        penumpangLabel = new javax.swing.JLabel();
        containerOptionMotor = new javax.swing.JPanel();
        motorRBtn = new javax.swing.JRadioButton();
        motorInput = new javax.swing.JTextField();
        takLabel = new javax.swing.JLabel();
        kelompokLabel = new javax.swing.JLabel();
        npm1Label = new javax.swing.JLabel();
        npm2Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        containerLabel.setPreferredSize(new java.awt.Dimension(750, 0));

        titleContent.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleContent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleContent.setText("OBJECT PERSISTENCE 1");

        btnAdd.setText("Tambah");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Ubah");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Hapus");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setText("Cari");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        containerInputId.setPreferredSize(new java.awt.Dimension(300, 65));

        idLabel.setText("ID Kendaraan");

        idInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerInputIdLayout = new javax.swing.GroupLayout(containerInputId);
        containerInputId.setLayout(containerInputIdLayout);
        containerInputIdLayout.setHorizontalGroup(
            containerInputIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputIdLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(containerInputIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerInputIdLayout.createSequentialGroup()
                        .addComponent(idLabel)
                        .addGap(0, 208, Short.MAX_VALUE))
                    .addComponent(idInput))
                .addContainerGap())
        );
        containerInputIdLayout.setVerticalGroup(
            containerInputIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputIdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containerInputMerk.setPreferredSize(new java.awt.Dimension(300, 65));

        merkLabel.setText("Merk");

        merkInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merkInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerInputMerkLayout = new javax.swing.GroupLayout(containerInputMerk);
        containerInputMerk.setLayout(containerInputMerkLayout);
        containerInputMerkLayout.setHorizontalGroup(
            containerInputMerkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputMerkLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(containerInputMerkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerInputMerkLayout.createSequentialGroup()
                        .addComponent(merkLabel)
                        .addGap(0, 252, Short.MAX_VALUE))
                    .addComponent(merkInput, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                .addContainerGap())
        );
        containerInputMerkLayout.setVerticalGroup(
            containerInputMerkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputMerkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(merkLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(merkInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containerInputTahun.setPreferredSize(new java.awt.Dimension(300, 65));

        tahunLabel.setText("Tahun Pembuatan");

        tahunInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerInputTahunLayout = new javax.swing.GroupLayout(containerInputTahun);
        containerInputTahun.setLayout(containerInputTahunLayout);
        containerInputTahunLayout.setHorizontalGroup(
            containerInputTahunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputTahunLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(containerInputTahunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerInputTahunLayout.createSequentialGroup()
                        .addComponent(tahunLabel)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(tahunInput, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                .addContainerGap())
        );
        containerInputTahunLayout.setVerticalGroup(
            containerInputTahunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputTahunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tahunLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tahunInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containerInputNoPlat.setPreferredSize(new java.awt.Dimension(300, 65));

        noPlatLabel.setText("No Plat");

        noPlatInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noPlatInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerInputNoPlatLayout = new javax.swing.GroupLayout(containerInputNoPlat);
        containerInputNoPlat.setLayout(containerInputNoPlatLayout);
        containerInputNoPlatLayout.setHorizontalGroup(
            containerInputNoPlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputNoPlatLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(containerInputNoPlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerInputNoPlatLayout.createSequentialGroup()
                        .addComponent(noPlatLabel)
                        .addGap(0, 241, Short.MAX_VALUE))
                    .addComponent(noPlatInput))
                .addContainerGap())
        );
        containerInputNoPlatLayout.setVerticalGroup(
            containerInputNoPlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputNoPlatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noPlatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noPlatInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSave.setText("Simpan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Batal");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        showDataTextArea.setEditable(false);
        showDataTextArea.setColumns(20);
        showDataTextArea.setRows(5);
        showDataTextArea.setPreferredSize(null);
        jScrollPane1.setViewportView(showDataTextArea);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout showDataPanelLayout = new javax.swing.GroupLayout(showDataPanel);
        showDataPanel.setLayout(showDataPanelLayout);
        showDataPanelLayout.setHorizontalGroup(
            showDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showDataPanelLayout.createSequentialGroup()
                .addContainerGap(401, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(showDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(showDataPanelLayout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 407, Short.MAX_VALUE)))
        );
        showDataPanelLayout.setVerticalGroup(
            showDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(showDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(showDataPanelLayout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        showDataPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane3});

        buttonGroup1.add(mobilRBtn);
        mobilRBtn.setText("Mobil");
        mobilRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilRBtnActionPerformed(evt);
            }
        });

        mobilInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilInputActionPerformed(evt);
            }
        });

        penumpangLabel.setText("Jumlah Penumpang");

        javax.swing.GroupLayout containerOptionMobilLayout = new javax.swing.GroupLayout(containerOptionMobil);
        containerOptionMobil.setLayout(containerOptionMobilLayout);
        containerOptionMobilLayout.setHorizontalGroup(
            containerOptionMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerOptionMobilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerOptionMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mobilRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobilInput, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(penumpangLabel))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        containerOptionMobilLayout.setVerticalGroup(
            containerOptionMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerOptionMobilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mobilRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(penumpangLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mobilInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        buttonGroup1.add(motorRBtn);
        motorRBtn.setText("Motor");
        motorRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorRBtnActionPerformed(evt);
            }
        });

        motorInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorInputActionPerformed(evt);
            }
        });

        takLabel.setText("Jenis Tak");

        javax.swing.GroupLayout containerOptionMotorLayout = new javax.swing.GroupLayout(containerOptionMotor);
        containerOptionMotor.setLayout(containerOptionMotorLayout);
        containerOptionMotorLayout.setHorizontalGroup(
            containerOptionMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerOptionMotorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerOptionMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(motorInput, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addGroup(containerOptionMotorLayout.createSequentialGroup()
                        .addGroup(containerOptionMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(motorRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(takLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        containerOptionMotorLayout.setVerticalGroup(
            containerOptionMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerOptionMotorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(motorRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(takLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(motorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kelompokLabel.setText("Kelompok 5");

        npm1Label.setText("210711015");

        npm2Label.setText("210711023");

        jLabel1.setText("Data Mobil");

        jLabel2.setText("Data Motor");

        javax.swing.GroupLayout containerLabelLayout = new javax.swing.GroupLayout(containerLabel);
        containerLabel.setLayout(containerLabelLayout);
        containerLabelLayout.setHorizontalGroup(
            containerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLabelLayout.createSequentialGroup()
                .addGroup(containerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLabelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(containerInputNoPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerLabelLayout.createSequentialGroup()
                        .addGroup(containerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLabelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(containerInputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(containerLabelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete))
                            .addGroup(containerLabelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(containerInputMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(containerLabelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(containerInputTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)))
                .addGroup(containerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(containerLabelLayout.createSequentialGroup()
                        .addGap(631, 631, 631)
                        .addGroup(containerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCancel)
                            .addGroup(containerLabelLayout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addGap(84, 84, 84))))
                    .addGroup(containerLabelLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(containerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(containerOptionMobil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(containerLabelLayout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch))
                            .addComponent(containerOptionMotor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(containerLabelLayout.createSequentialGroup()
                .addGroup(containerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLabelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(containerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kelompokLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(npm1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(npm2Label)
                        .addGap(80, 80, 80)
                        .addComponent(titleContent))
                    .addGroup(containerLabelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(containerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(containerLabelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1)
                                .addGap(348, 348, 348)
                                .addComponent(jLabel2)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        containerLabelLayout.setVerticalGroup(
            containerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLabelLayout.createSequentialGroup()
                .addGroup(containerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(containerLabelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(titleContent))
                    .addGroup(containerLabelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kelompokLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(containerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(npm1Label)
                            .addComponent(npm2Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(containerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(containerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(containerOptionMobil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(containerInputId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(containerOptionMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(containerLabelLayout.createSequentialGroup()
                        .addComponent(containerInputMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(containerInputTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(containerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLabelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(containerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnCancel)))
                    .addGroup(containerLabelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(containerInputNoPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(containerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane2.setViewportView(containerLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        setComponent(true);
        motorInput.setEnabled(false);
        mobilInput.setEnabled(false);
        clearText();
        txtSearch.setText("");
        action = "Tambah";
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        setComponent(true);
        motorInput.setEnabled(false);
        mobilInput.setEnabled(false);
        idInput.setEnabled(false);
        action = "Ubah";
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
//        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
//
//        if (getAnswer == JOptionPane.YES_OPTION){
//                try{
//                    dosenControl.deleteDataDosen(nidInput.getText());
//                    clearText();
//                    showDosen();
//                    JOptionPane.showMessageDialog(null, "Data Berhasil dihapus!");
//                }catch (Exception e){
//                    System.out.println("Error : "+ e.getMessage());
//                } 
//        }else{
//            JOptionPane.showMessageDialog(null,"Data tidak jadi dihapus");
//        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        setEditDeleteBtn(true);
        setComponent(false);
        setSelect(false);
        
//        try{
//            Dosen dosen = dosenControl.searchDosen(txtSearch.getText());
//            if(dosen == null){
//                setEditDeleteBtn(false);
//                JOptionPane.showMessageDialog(null, "Data tidak ditemukan", "konfirmasi", JOptionPane.DEFAULT_OPTION);
//            }else{
//                nidInput.setText(dosen.getNomorIndukDosen());
//                namaInput.setText(dosen.getNama());
//                emailInput.setText(dosen.getEmail());
//                handphoneInput.setText(dosen.getNoHandphone());
//                if(){
//                    
//                }else{
//                    
//                }
//            }
//        }catch(Exception e){
//            System.out.println("Error: "+ e.getMessage());
//        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void idInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idInputActionPerformed

    private void merkInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merkInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_merkInputActionPerformed

    private void tahunInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunInputActionPerformed

    private void noPlatInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noPlatInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noPlatInputActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
//        try{
//            inputKosongException();
//            noIndukDosenException();
//            
//            Dosen d = new Dosen(nidInput.getText(), namaInput.getText(), emailInput.getText(), handphoneInput.getText());
//            if(action.equals("Tambah")){
//                dosenControl.insertDataDosen(d);
//            }else{
//                dosenControl.updateDataDosen(d,nidInput.getText());
//            }
//            clearText();
//            showDosen();
//            setComponent(false);
//            setEditDeleteBtn(false);
//        }catch(InputKosongException e){
//            JOptionPane.showMessageDialog(this, e.message());
//        }catch(NoIndukDosenException e){
//            JOptionPane.showMessageDialog(this, e.message());
//        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void mobilInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilInputActionPerformed

    private void mobilRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilRBtnActionPerformed
        // TODO add your handling code here:
        mobilRBtn.setEnabled(true);
        mobilInput.setEnabled(true);
        motorInput.setEnabled(false);
        motorInput.setText("");
    }//GEN-LAST:event_mobilRBtnActionPerformed

    private void motorRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorRBtnActionPerformed
        // TODO add your handling code here:
        motorRBtn.setEnabled(true);
        motorInput.setEnabled(true);
        mobilInput.setEnabled(false);
        mobilInput.setText("");
    }//GEN-LAST:event_motorRBtnActionPerformed

    private void motorInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motorInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemplateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemplateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemplateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemplateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemplateView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel containerInputId;
    private javax.swing.JPanel containerInputMerk;
    private javax.swing.JPanel containerInputNoPlat;
    private javax.swing.JPanel containerInputTahun;
    private javax.swing.JPanel containerLabel;
    private javax.swing.JPanel containerOptionMobil;
    private javax.swing.JPanel containerOptionMotor;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel kelompokLabel;
    private javax.swing.JTextField merkInput;
    private javax.swing.JLabel merkLabel;
    private javax.swing.JTextField mobilInput;
    private javax.swing.JRadioButton mobilRBtn;
    private javax.swing.JTextField motorInput;
    private javax.swing.JRadioButton motorRBtn;
    private javax.swing.JTextField noPlatInput;
    private javax.swing.JLabel noPlatLabel;
    private javax.swing.JLabel npm1Label;
    private javax.swing.JLabel npm2Label;
    private javax.swing.JLabel penumpangLabel;
    private javax.swing.JPanel showDataPanel;
    private javax.swing.JTextArea showDataTextArea;
    private javax.swing.JTextField tahunInput;
    private javax.swing.JLabel tahunLabel;
    private javax.swing.JLabel takLabel;
    private javax.swing.JLabel titleContent;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
